spring:
  datasource:
    password: samb
    url: jdbc:mysql://localhost:3306/ticket_schema
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
  server:
    error:
      include-message: always
      include-binding-errors: always
      include-stacktrace: on_trace_param
      include-exception: false